//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 3/3/2014 21:40:22
namespace ShowManager.Client.WPF.ShowManagement
{
    
    /// <summary>
    /// There are no comments for ShowManagementDBEntities in the schema.
    /// </summary>
    public partial class ShowManagementDBEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new ShowManagementDBEntities object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ShowManagementDBEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("ShowManagementDBModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("ShowManager.Client.WPF.ShowManagement", typeName.Substring(21)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("ShowManager.Client.WPF.ShowManagement", global::System.StringComparison.Ordinal))
            {
                return string.Concat("ShowManagementDBModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for ApplicationInstances in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ApplicationInstance> ApplicationInstances
        {
            get
            {
                if ((this._ApplicationInstances == null))
                {
                    this._ApplicationInstances = base.CreateQuery<ApplicationInstance>("ApplicationInstances");
                }
                return this._ApplicationInstances;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ApplicationInstance> _ApplicationInstances;
        /// <summary>
        /// There are no comments for Parsers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Parser> Parsers
        {
            get
            {
                if ((this._Parsers == null))
                {
                    this._Parsers = base.CreateQuery<Parser>("Parsers");
                }
                return this._Parsers;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Parser> _Parsers;
        /// <summary>
        /// There are no comments for ParserTypes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ParserType> ParserTypes
        {
            get
            {
                if ((this._ParserTypes == null))
                {
                    this._ParserTypes = base.CreateQuery<ParserType>("ParserTypes");
                }
                return this._ParserTypes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ParserType> _ParserTypes;
        /// <summary>
        /// There are no comments for Shows in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Show> Shows
        {
            get
            {
                if ((this._Shows == null))
                {
                    this._Shows = base.CreateQuery<Show>("Shows");
                }
                return this._Shows;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Show> _Shows;
        /// <summary>
        /// There are no comments for ShowParsers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ShowParser> ShowParsers
        {
            get
            {
                if ((this._ShowParsers == null))
                {
                    this._ShowParsers = base.CreateQuery<ShowParser>("ShowParsers");
                }
                return this._ShowParsers;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ShowParser> _ShowParsers;
        /// <summary>
        /// There are no comments for ApplicationInstances in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToApplicationInstances(ApplicationInstance applicationInstance)
        {
            base.AddObject("ApplicationInstances", applicationInstance);
        }
        /// <summary>
        /// There are no comments for Parsers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToParsers(Parser parser)
        {
            base.AddObject("Parsers", parser);
        }
        /// <summary>
        /// There are no comments for ParserTypes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToParserTypes(ParserType parserType)
        {
            base.AddObject("ParserTypes", parserType);
        }
        /// <summary>
        /// There are no comments for Shows in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToShows(Show show)
        {
            base.AddObject("Shows", show);
        }
        /// <summary>
        /// There are no comments for ShowParsers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToShowParsers(ShowParser showParser)
        {
            base.AddObject("ShowParsers", showParser);
        }
    }
    /// <summary>
    /// There are no comments for ShowManagementDBModel.ApplicationInstance in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ApplicationInstanceKey
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ApplicationInstances")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ApplicationInstanceKey")]
    public partial class ApplicationInstance : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ApplicationInstance object.
        /// </summary>
        /// <param name="applicationInstanceKey">Initial value of ApplicationInstanceKey.</param>
        /// <param name="machineKey">Initial value of MachineKey.</param>
        /// <param name="description">Initial value of Description.</param>
        /// <param name="createdBy">Initial value of CreatedBy.</param>
        /// <param name="createdDtm">Initial value of CreatedDtm.</param>
        /// <param name="modifiedBy">Initial value of ModifiedBy.</param>
        /// <param name="modifiedDtm">Initial value of ModifiedDtm.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ApplicationInstance CreateApplicationInstance(int applicationInstanceKey, string machineKey, string description, string createdBy, global::System.DateTime createdDtm, string modifiedBy, global::System.DateTime modifiedDtm)
        {
            ApplicationInstance applicationInstance = new ApplicationInstance();
            applicationInstance.ApplicationInstanceKey = applicationInstanceKey;
            applicationInstance.MachineKey = machineKey;
            applicationInstance.Description = description;
            applicationInstance.CreatedBy = createdBy;
            applicationInstance.CreatedDtm = createdDtm;
            applicationInstance.ModifiedBy = modifiedBy;
            applicationInstance.ModifiedDtm = modifiedDtm;
            return applicationInstance;
        }
        /// <summary>
        /// There are no comments for Property ApplicationInstanceKey in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ApplicationInstanceKey
        {
            get
            {
                return this._ApplicationInstanceKey;
            }
            set
            {
                this.OnApplicationInstanceKeyChanging(value);
                this._ApplicationInstanceKey = value;
                this.OnApplicationInstanceKeyChanged();
                this.OnPropertyChanged("ApplicationInstanceKey");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ApplicationInstanceKey;
        partial void OnApplicationInstanceKeyChanging(int value);
        partial void OnApplicationInstanceKeyChanged();
        /// <summary>
        /// There are no comments for Property MachineKey in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MachineKey
        {
            get
            {
                return this._MachineKey;
            }
            set
            {
                this.OnMachineKeyChanging(value);
                this._MachineKey = value;
                this.OnMachineKeyChanged();
                this.OnPropertyChanged("MachineKey");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MachineKey;
        partial void OnMachineKeyChanging(string value);
        partial void OnMachineKeyChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property CreatedDtm in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime CreatedDtm
        {
            get
            {
                return this._CreatedDtm;
            }
            set
            {
                this.OnCreatedDtmChanging(value);
                this._CreatedDtm = value;
                this.OnCreatedDtmChanged();
                this.OnPropertyChanged("CreatedDtm");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _CreatedDtm;
        partial void OnCreatedDtmChanging(global::System.DateTime value);
        partial void OnCreatedDtmChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDtm in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime ModifiedDtm
        {
            get
            {
                return this._ModifiedDtm;
            }
            set
            {
                this.OnModifiedDtmChanging(value);
                this._ModifiedDtm = value;
                this.OnModifiedDtmChanged();
                this.OnPropertyChanged("ModifiedDtm");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _ModifiedDtm;
        partial void OnModifiedDtmChanging(global::System.DateTime value);
        partial void OnModifiedDtmChanged();
        /// <summary>
        /// There are no comments for Parsers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Parser> Parsers
        {
            get
            {
                return this._Parsers;
            }
            set
            {
                this._Parsers = value;
                this.OnPropertyChanged("Parsers");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Parser> _Parsers = new global::System.Data.Services.Client.DataServiceCollection<Parser>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Shows in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Show> Shows
        {
            get
            {
                return this._Shows;
            }
            set
            {
                this._Shows = value;
                this.OnPropertyChanged("Shows");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Show> _Shows = new global::System.Data.Services.Client.DataServiceCollection<Show>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for ShowParsers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<ShowParser> ShowParsers
        {
            get
            {
                return this._ShowParsers;
            }
            set
            {
                this._ShowParsers = value;
                this.OnPropertyChanged("ShowParsers");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<ShowParser> _ShowParsers = new global::System.Data.Services.Client.DataServiceCollection<ShowParser>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ShowManagementDBModel.Parser in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ParserKey
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Parsers")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ParserKey")]
    public partial class Parser : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Parser object.
        /// </summary>
        /// <param name="parserKey">Initial value of ParserKey.</param>
        /// <param name="appInstanceKey">Initial value of AppInstanceKey.</param>
        /// <param name="parserTypeKey">Initial value of ParserTypeKey.</param>
        /// <param name="pattern">Initial value of Pattern.</param>
        /// <param name="excludedCharacters">Initial value of ExcludedCharacters.</param>
        /// <param name="createdBy">Initial value of CreatedBy.</param>
        /// <param name="createdDtm">Initial value of CreatedDtm.</param>
        /// <param name="modifiedBy">Initial value of ModifiedBy.</param>
        /// <param name="modifiedDtm">Initial value of ModifiedDtm.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Parser CreateParser(int parserKey, int appInstanceKey, int parserTypeKey, string pattern, string excludedCharacters, string createdBy, global::System.DateTime createdDtm, string modifiedBy, global::System.DateTime modifiedDtm)
        {
            Parser parser = new Parser();
            parser.ParserKey = parserKey;
            parser.AppInstanceKey = appInstanceKey;
            parser.ParserTypeKey = parserTypeKey;
            parser.Pattern = pattern;
            parser.ExcludedCharacters = excludedCharacters;
            parser.CreatedBy = createdBy;
            parser.CreatedDtm = createdDtm;
            parser.ModifiedBy = modifiedBy;
            parser.ModifiedDtm = modifiedDtm;
            return parser;
        }
        /// <summary>
        /// There are no comments for Property ParserKey in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ParserKey
        {
            get
            {
                return this._ParserKey;
            }
            set
            {
                this.OnParserKeyChanging(value);
                this._ParserKey = value;
                this.OnParserKeyChanged();
                this.OnPropertyChanged("ParserKey");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ParserKey;
        partial void OnParserKeyChanging(int value);
        partial void OnParserKeyChanged();
        /// <summary>
        /// There are no comments for Property AppInstanceKey in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int AppInstanceKey
        {
            get
            {
                return this._AppInstanceKey;
            }
            set
            {
                this.OnAppInstanceKeyChanging(value);
                this._AppInstanceKey = value;
                this.OnAppInstanceKeyChanged();
                this.OnPropertyChanged("AppInstanceKey");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _AppInstanceKey;
        partial void OnAppInstanceKeyChanging(int value);
        partial void OnAppInstanceKeyChanged();
        /// <summary>
        /// There are no comments for Property ParserTypeKey in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ParserTypeKey
        {
            get
            {
                return this._ParserTypeKey;
            }
            set
            {
                this.OnParserTypeKeyChanging(value);
                this._ParserTypeKey = value;
                this.OnParserTypeKeyChanged();
                this.OnPropertyChanged("ParserTypeKey");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ParserTypeKey;
        partial void OnParserTypeKeyChanging(int value);
        partial void OnParserTypeKeyChanged();
        /// <summary>
        /// There are no comments for Property Pattern in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Pattern
        {
            get
            {
                return this._Pattern;
            }
            set
            {
                this.OnPatternChanging(value);
                this._Pattern = value;
                this.OnPatternChanged();
                this.OnPropertyChanged("Pattern");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Pattern;
        partial void OnPatternChanging(string value);
        partial void OnPatternChanged();
        /// <summary>
        /// There are no comments for Property ExcludedCharacters in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ExcludedCharacters
        {
            get
            {
                return this._ExcludedCharacters;
            }
            set
            {
                this.OnExcludedCharactersChanging(value);
                this._ExcludedCharacters = value;
                this.OnExcludedCharactersChanged();
                this.OnPropertyChanged("ExcludedCharacters");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ExcludedCharacters;
        partial void OnExcludedCharactersChanging(string value);
        partial void OnExcludedCharactersChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property CreatedDtm in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime CreatedDtm
        {
            get
            {
                return this._CreatedDtm;
            }
            set
            {
                this.OnCreatedDtmChanging(value);
                this._CreatedDtm = value;
                this.OnCreatedDtmChanged();
                this.OnPropertyChanged("CreatedDtm");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _CreatedDtm;
        partial void OnCreatedDtmChanging(global::System.DateTime value);
        partial void OnCreatedDtmChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDtm in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime ModifiedDtm
        {
            get
            {
                return this._ModifiedDtm;
            }
            set
            {
                this.OnModifiedDtmChanging(value);
                this._ModifiedDtm = value;
                this.OnModifiedDtmChanged();
                this.OnPropertyChanged("ModifiedDtm");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _ModifiedDtm;
        partial void OnModifiedDtmChanging(global::System.DateTime value);
        partial void OnModifiedDtmChanged();
        /// <summary>
        /// There are no comments for ApplicationInstance in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ApplicationInstance ApplicationInstance
        {
            get
            {
                return this._ApplicationInstance;
            }
            set
            {
                this._ApplicationInstance = value;
                this.OnPropertyChanged("ApplicationInstance");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private ApplicationInstance _ApplicationInstance;
        /// <summary>
        /// There are no comments for ParserType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ParserType ParserType
        {
            get
            {
                return this._ParserType;
            }
            set
            {
                this._ParserType = value;
                this.OnPropertyChanged("ParserType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private ParserType _ParserType;
        /// <summary>
        /// There are no comments for ShowParsers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<ShowParser> ShowParsers
        {
            get
            {
                return this._ShowParsers;
            }
            set
            {
                this._ShowParsers = value;
                this.OnPropertyChanged("ShowParsers");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<ShowParser> _ShowParsers = new global::System.Data.Services.Client.DataServiceCollection<ShowParser>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ShowManagementDBModel.ParserType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ParserTypeKey
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ParserTypes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ParserTypeKey")]
    public partial class ParserType : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ParserType object.
        /// </summary>
        /// <param name="parserTypeKey">Initial value of ParserTypeKey.</param>
        /// <param name="code">Initial value of Code.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="sortSeq">Initial value of SortSeq.</param>
        /// <param name="createdBy">Initial value of CreatedBy.</param>
        /// <param name="createdDtm">Initial value of CreatedDtm.</param>
        /// <param name="modifiedBy">Initial value of ModifiedBy.</param>
        /// <param name="modifiedDtm">Initial value of ModifiedDtm.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ParserType CreateParserType(int parserTypeKey, string code, string name, int sortSeq, string createdBy, global::System.DateTime createdDtm, string modifiedBy, global::System.DateTime modifiedDtm)
        {
            ParserType parserType = new ParserType();
            parserType.ParserTypeKey = parserTypeKey;
            parserType.Code = code;
            parserType.Name = name;
            parserType.SortSeq = sortSeq;
            parserType.CreatedBy = createdBy;
            parserType.CreatedDtm = createdDtm;
            parserType.ModifiedBy = modifiedBy;
            parserType.ModifiedDtm = modifiedDtm;
            return parserType;
        }
        /// <summary>
        /// There are no comments for Property ParserTypeKey in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ParserTypeKey
        {
            get
            {
                return this._ParserTypeKey;
            }
            set
            {
                this.OnParserTypeKeyChanging(value);
                this._ParserTypeKey = value;
                this.OnParserTypeKeyChanged();
                this.OnPropertyChanged("ParserTypeKey");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ParserTypeKey;
        partial void OnParserTypeKeyChanging(int value);
        partial void OnParserTypeKeyChanged();
        /// <summary>
        /// There are no comments for Property Code in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                this.OnCodeChanging(value);
                this._Code = value;
                this.OnCodeChanged();
                this.OnPropertyChanged("Code");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Code;
        partial void OnCodeChanging(string value);
        partial void OnCodeChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property SortSeq in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SortSeq
        {
            get
            {
                return this._SortSeq;
            }
            set
            {
                this.OnSortSeqChanging(value);
                this._SortSeq = value;
                this.OnSortSeqChanged();
                this.OnPropertyChanged("SortSeq");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SortSeq;
        partial void OnSortSeqChanging(int value);
        partial void OnSortSeqChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property CreatedDtm in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime CreatedDtm
        {
            get
            {
                return this._CreatedDtm;
            }
            set
            {
                this.OnCreatedDtmChanging(value);
                this._CreatedDtm = value;
                this.OnCreatedDtmChanged();
                this.OnPropertyChanged("CreatedDtm");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _CreatedDtm;
        partial void OnCreatedDtmChanging(global::System.DateTime value);
        partial void OnCreatedDtmChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDtm in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime ModifiedDtm
        {
            get
            {
                return this._ModifiedDtm;
            }
            set
            {
                this.OnModifiedDtmChanging(value);
                this._ModifiedDtm = value;
                this.OnModifiedDtmChanged();
                this.OnPropertyChanged("ModifiedDtm");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _ModifiedDtm;
        partial void OnModifiedDtmChanging(global::System.DateTime value);
        partial void OnModifiedDtmChanged();
        /// <summary>
        /// There are no comments for Parsers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Parser> Parsers
        {
            get
            {
                return this._Parsers;
            }
            set
            {
                this._Parsers = value;
                this.OnPropertyChanged("Parsers");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Parser> _Parsers = new global::System.Data.Services.Client.DataServiceCollection<Parser>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ShowManagementDBModel.Show in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ShowKey
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Shows")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ShowKey")]
    public partial class Show : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Show object.
        /// </summary>
        /// <param name="showKey">Initial value of ShowKey.</param>
        /// <param name="appInstanceKey">Initial value of AppInstanceKey.</param>
        /// <param name="tvdbId">Initial value of TvdbId.</param>
        /// <param name="title">Initial value of Title.</param>
        /// <param name="directory">Initial value of Directory.</param>
        /// <param name="createdBy">Initial value of CreatedBy.</param>
        /// <param name="createdDtm">Initial value of CreatedDtm.</param>
        /// <param name="modifiedBy">Initial value of ModifiedBy.</param>
        /// <param name="modifiedDtm">Initial value of ModifiedDtm.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Show CreateShow(int showKey, int appInstanceKey, long tvdbId, string title, string directory, string createdBy, global::System.DateTime createdDtm, string modifiedBy, global::System.DateTime modifiedDtm)
        {
            Show show = new Show();
            show.ShowKey = showKey;
            show.AppInstanceKey = appInstanceKey;
            show.TvdbId = tvdbId;
            show.Title = title;
            show.Directory = directory;
            show.CreatedBy = createdBy;
            show.CreatedDtm = createdDtm;
            show.ModifiedBy = modifiedBy;
            show.ModifiedDtm = modifiedDtm;
            return show;
        }
        /// <summary>
        /// There are no comments for Property ShowKey in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ShowKey
        {
            get
            {
                return this._ShowKey;
            }
            set
            {
                this.OnShowKeyChanging(value);
                this._ShowKey = value;
                this.OnShowKeyChanged();
                this.OnPropertyChanged("ShowKey");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ShowKey;
        partial void OnShowKeyChanging(int value);
        partial void OnShowKeyChanged();
        /// <summary>
        /// There are no comments for Property AppInstanceKey in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int AppInstanceKey
        {
            get
            {
                return this._AppInstanceKey;
            }
            set
            {
                this.OnAppInstanceKeyChanging(value);
                this._AppInstanceKey = value;
                this.OnAppInstanceKeyChanged();
                this.OnPropertyChanged("AppInstanceKey");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _AppInstanceKey;
        partial void OnAppInstanceKeyChanging(int value);
        partial void OnAppInstanceKeyChanged();
        /// <summary>
        /// There are no comments for Property TvdbId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long TvdbId
        {
            get
            {
                return this._TvdbId;
            }
            set
            {
                this.OnTvdbIdChanging(value);
                this._TvdbId = value;
                this.OnTvdbIdChanged();
                this.OnPropertyChanged("TvdbId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _TvdbId;
        partial void OnTvdbIdChanging(long value);
        partial void OnTvdbIdChanged();
        /// <summary>
        /// There are no comments for Property ImdbId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ImdbId
        {
            get
            {
                return this._ImdbId;
            }
            set
            {
                this.OnImdbIdChanging(value);
                this._ImdbId = value;
                this.OnImdbIdChanged();
                this.OnPropertyChanged("ImdbId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ImdbId;
        partial void OnImdbIdChanging(string value);
        partial void OnImdbIdChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Directory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Directory
        {
            get
            {
                return this._Directory;
            }
            set
            {
                this.OnDirectoryChanging(value);
                this._Directory = value;
                this.OnDirectoryChanged();
                this.OnPropertyChanged("Directory");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Directory;
        partial void OnDirectoryChanging(string value);
        partial void OnDirectoryChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property CreatedDtm in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime CreatedDtm
        {
            get
            {
                return this._CreatedDtm;
            }
            set
            {
                this.OnCreatedDtmChanging(value);
                this._CreatedDtm = value;
                this.OnCreatedDtmChanged();
                this.OnPropertyChanged("CreatedDtm");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _CreatedDtm;
        partial void OnCreatedDtmChanging(global::System.DateTime value);
        partial void OnCreatedDtmChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDtm in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime ModifiedDtm
        {
            get
            {
                return this._ModifiedDtm;
            }
            set
            {
                this.OnModifiedDtmChanging(value);
                this._ModifiedDtm = value;
                this.OnModifiedDtmChanged();
                this.OnPropertyChanged("ModifiedDtm");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _ModifiedDtm;
        partial void OnModifiedDtmChanging(global::System.DateTime value);
        partial void OnModifiedDtmChanged();
        /// <summary>
        /// There are no comments for ApplicationInstance in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ApplicationInstance ApplicationInstance
        {
            get
            {
                return this._ApplicationInstance;
            }
            set
            {
                this._ApplicationInstance = value;
                this.OnPropertyChanged("ApplicationInstance");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private ApplicationInstance _ApplicationInstance;
        /// <summary>
        /// There are no comments for ShowParsers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<ShowParser> ShowParsers
        {
            get
            {
                return this._ShowParsers;
            }
            set
            {
                this._ShowParsers = value;
                this.OnPropertyChanged("ShowParsers");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<ShowParser> _ShowParsers = new global::System.Data.Services.Client.DataServiceCollection<ShowParser>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ShowManagementDBModel.ShowParser in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ShowParserKey
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ShowParsers")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ShowParserKey")]
    public partial class ShowParser : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ShowParser object.
        /// </summary>
        /// <param name="showParserKey">Initial value of ShowParserKey.</param>
        /// <param name="appInstanceKey">Initial value of AppInstanceKey.</param>
        /// <param name="showKey">Initial value of ShowKey.</param>
        /// <param name="parserKey">Initial value of ParserKey.</param>
        /// <param name="createdBy">Initial value of CreatedBy.</param>
        /// <param name="createdDtm">Initial value of CreatedDtm.</param>
        /// <param name="modifiedBy">Initial value of ModifiedBy.</param>
        /// <param name="modifiedDtm">Initial value of ModifiedDtm.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ShowParser CreateShowParser(int showParserKey, int appInstanceKey, int showKey, int parserKey, string createdBy, global::System.DateTime createdDtm, string modifiedBy, global::System.DateTime modifiedDtm)
        {
            ShowParser showParser = new ShowParser();
            showParser.ShowParserKey = showParserKey;
            showParser.AppInstanceKey = appInstanceKey;
            showParser.ShowKey = showKey;
            showParser.ParserKey = parserKey;
            showParser.CreatedBy = createdBy;
            showParser.CreatedDtm = createdDtm;
            showParser.ModifiedBy = modifiedBy;
            showParser.ModifiedDtm = modifiedDtm;
            return showParser;
        }
        /// <summary>
        /// There are no comments for Property ShowParserKey in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ShowParserKey
        {
            get
            {
                return this._ShowParserKey;
            }
            set
            {
                this.OnShowParserKeyChanging(value);
                this._ShowParserKey = value;
                this.OnShowParserKeyChanged();
                this.OnPropertyChanged("ShowParserKey");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ShowParserKey;
        partial void OnShowParserKeyChanging(int value);
        partial void OnShowParserKeyChanged();
        /// <summary>
        /// There are no comments for Property AppInstanceKey in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int AppInstanceKey
        {
            get
            {
                return this._AppInstanceKey;
            }
            set
            {
                this.OnAppInstanceKeyChanging(value);
                this._AppInstanceKey = value;
                this.OnAppInstanceKeyChanged();
                this.OnPropertyChanged("AppInstanceKey");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _AppInstanceKey;
        partial void OnAppInstanceKeyChanging(int value);
        partial void OnAppInstanceKeyChanged();
        /// <summary>
        /// There are no comments for Property ShowKey in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ShowKey
        {
            get
            {
                return this._ShowKey;
            }
            set
            {
                this.OnShowKeyChanging(value);
                this._ShowKey = value;
                this.OnShowKeyChanged();
                this.OnPropertyChanged("ShowKey");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ShowKey;
        partial void OnShowKeyChanging(int value);
        partial void OnShowKeyChanged();
        /// <summary>
        /// There are no comments for Property ParserKey in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ParserKey
        {
            get
            {
                return this._ParserKey;
            }
            set
            {
                this.OnParserKeyChanging(value);
                this._ParserKey = value;
                this.OnParserKeyChanged();
                this.OnPropertyChanged("ParserKey");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ParserKey;
        partial void OnParserKeyChanging(int value);
        partial void OnParserKeyChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property CreatedDtm in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime CreatedDtm
        {
            get
            {
                return this._CreatedDtm;
            }
            set
            {
                this.OnCreatedDtmChanging(value);
                this._CreatedDtm = value;
                this.OnCreatedDtmChanged();
                this.OnPropertyChanged("CreatedDtm");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _CreatedDtm;
        partial void OnCreatedDtmChanging(global::System.DateTime value);
        partial void OnCreatedDtmChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDtm in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime ModifiedDtm
        {
            get
            {
                return this._ModifiedDtm;
            }
            set
            {
                this.OnModifiedDtmChanging(value);
                this._ModifiedDtm = value;
                this.OnModifiedDtmChanged();
                this.OnPropertyChanged("ModifiedDtm");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _ModifiedDtm;
        partial void OnModifiedDtmChanging(global::System.DateTime value);
        partial void OnModifiedDtmChanged();
        /// <summary>
        /// There are no comments for ApplicationInstance in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ApplicationInstance ApplicationInstance
        {
            get
            {
                return this._ApplicationInstance;
            }
            set
            {
                this._ApplicationInstance = value;
                this.OnPropertyChanged("ApplicationInstance");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private ApplicationInstance _ApplicationInstance;
        /// <summary>
        /// There are no comments for Parser in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Parser Parser
        {
            get
            {
                return this._Parser;
            }
            set
            {
                this._Parser = value;
                this.OnPropertyChanged("Parser");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Parser _Parser;
        /// <summary>
        /// There are no comments for Show in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Show Show
        {
            get
            {
                return this._Show;
            }
            set
            {
                this._Show = value;
                this.OnPropertyChanged("Show");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Show _Show;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
