//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowManagerAzureWebRole
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationInstance
    {
        public ApplicationInstance()
        {
            this.Parsers = new HashSet<Parser>();
            this.Shows = new HashSet<Show>();
        }
    
        public int ApplicationInstanceKey { get; set; }
        public string MachineKey { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDtm { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDtm { get; set; }
    
        public virtual ICollection<Parser> Parsers { get; set; }
        public virtual ICollection<Show> Shows { get; set; }
    }
}
