//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowManagerAzureWebRole
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityTypeMaster
    {
        public int EntityTypeMasterKey { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Provider { get; set; }
        public string RepositoryProvider { get; set; }
        public string BaseProvider { get; set; }
        public int SortSeq { get; set; }
        public bool IsCacheable { get; set; }
        public bool IsComparable { get; set; }
        public string ComparableFieldName { get; set; }
        public string EquatableFieldName { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDtm { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDtm { get; set; }
    }
}
