//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowManagerAzureWebRole
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnumMaster
    {
        public int EnumMasterKey { get; set; }
        public string TableName { get; set; }
        public string PrimaryKeyName { get; set; }
        public string CodeName { get; set; }
        public string EnumName { get; set; }
        public string DescriptionName { get; set; }
        public bool IsBitwise { get; set; }
        public bool GenerateDefault { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDtm { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDtm { get; set; }
    }
}
