//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowManagerAzureWebRole
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParserType
    {
        public ParserType()
        {
            this.Parsers = new HashSet<Parser>();
        }
    
        public int ParserTypeKey { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int SortSeq { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDtm { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDtm { get; set; }
    
        public virtual ICollection<Parser> Parsers { get; set; }
    }
}
