//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowManagerAzureWebRole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Show
    {
        public Show()
        {
            this.ShowParsers = new HashSet<ShowParser>();
        }
    
        public int ShowKey { get; set; }
        public int AppInstanceKey { get; set; }
        public long TvdbId { get; set; }
        public string ImdbId { get; set; }
        public string Title { get; set; }
        public string Directory { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDtm { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDtm { get; set; }
    
        public virtual ApplicationInstance ApplicationInstance { get; set; }
        public virtual ICollection<ShowParser> ShowParsers { get; set; }
    }
}
