//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowManagerAzureWebRole
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShowManagementDBEntities : DbContext
    {
        public ShowManagementDBEntities()
            : base("name=ShowManagementDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ApplicationInstance> ApplicationInstances { get; set; }
        public DbSet<EntityTypeMaster> EntityTypeMasters { get; set; }
        public DbSet<EnumMaster> EnumMasters { get; set; }
        public DbSet<Parser> Parsers { get; set; }
        public DbSet<ParserType> ParserTypes { get; set; }
        public DbSet<Show> Shows { get; set; }
        public DbSet<ShowParser> ShowParsers { get; set; }
    }
}
